on: 
  push:
    branches: [ "master" , "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: display
      run: |
         echo "This demo file shows a" 
         
   
 
